### ISSUE TITLE
Would this tool work with Jira Cloud or only Jira Server?

### ISSUE THREAD

**Issue by Zatox** [KilskyreMan/JiraToTfs#7]
I'm trying to import a project that lives in Jira cloud without success. I keep getting a "JIRA returned status: Unauthorized". 
I've tried multiple times to make sure my credentials were right and another person tried as well. We both have administrators rights on the project.
I also verified that the REST API is working. I was able to successfully load user stories in JSON by hitting https://subdomain.jira.com/rest/api/latest/issue/[ProjectKey]-[IssueNumber]
I get he feeling that this tool was designed to work with Jira Server.

Has anyone been able to make this work with the cloud version?

**Comment by KilskyreMan** [comment]
Sorry to hear you are having problems Quentin.

You are right - Tool was only tested against server. Will update wiki to say so.

In theory it should work against cloud so will investigate.

You get authorisation failure if either you specify a wrong url, project key, user credentials.

Will get back to you soon.

Ian.

Sent from Outlook Mobilehttps://aka.ms/blhgte

On Fri, Apr 8, 2016 at 1:23 PM -0700, "Quentin Carissimo" <notifications@github.com<mailto:notifications@github.com>> wrote:

I'm trying to import a project that lives in Jira cloud without success. I keep getting a "JIRA returned status: Unauthorized".
I've tried multiple times to make sure my credentials were right and another person tried as well. We both have administrators rights on the project.
I also verified that the REST API is working. I was able to successfully load user stories in JSON by hitting https://subdomain.jira.com/rest/api/latest/issue/[ProjectKey]-[IssueNumber]https://subdomain.jira.com/rest/api/latest/issue/%5BProjectKey%5D-%5BIssueNumber%5D
I get he feeling that this tool was designed to work with Jira Server.

Has anyone been able to make this work with the cloud version?

## 

You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHubhttps://github.com/KilskyreMan/JiraToTfs/issues/7

If you've received this email by mistake, we're sorry for bothering you. It may contain information that's confidential, so please delete it without sharing it. And if you let us know, we can try to stop it from happening again. Thank you. We may monitor any emails sent or received by us, or on our behalf. If we do, this will be in line with relevant law and our own policies.

Sage Ireland, trading name of Sage Hibernia Limited. Registered in Ireland at One Central Park, Leopardstown, Dublin 18, Ireland. Registered number 300549.

Directors: L Perkins (UK) and M Parry (UK).

**Comment by Zatox** [comment]
Hello Ian,
First of all thanks for the quick reply and for open sourcing your project.

I found what the issue was and I'm sorry if you wasted time on this :

I've always used my email address to log in to Jira cloud so I thought it was my username when my actual username doesn't contain the domain part. So the problem was I had an extra '@example.com'

It's still not working for me at this time but since it doesn't seem related I'll open another issue.

I'm closing this issue though as authentication to Jira cloud is working fine
